source 'https://cdn.cocoapods.org'
platform :ios, '16.0'

install! 'cocoapods', :deterministic_uuids => false

use_frameworks!
inhibit_all_warnings!

target 'iosApp' do
  pod 'ComposeApp', :path => '../composeApp'
  pod 'FirebaseAnalytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'

      if config.name == 'Release'
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      end
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.targets.each do |target|
      target.build_phases.each do |build_phase|
        next unless build_phase.respond_to?(:name)
        next unless build_phase.name == '[CP-User] Build ComposeApp'
        build_phase.always_out_of_date = '1'
      end
    end
    aggregate_target.user_project.save
  end

end